### ISSUE TITLE
A little question

### ISSUE THREAD

**Issue by katsukuro** [yuusakurisub/WidevineCdm#1]
Hello, does this work for Microsoft Edge Widevine decryptor? If so what is the password to the files, I would really appreciate it!

**Comment by yuusakurisub** [comment]
I got the file from the URL below.
https://gofile.io/d/t6qwBQ

This is WidevineCdm for widevine-l3-decryptor to work.

**Comment by katsukuro** [comment]
just making sure, is this for Chrome of Microsoft Edge? I assume it's for Microsoft Edge by the name of it.

**Comment by yuusakurisub** [comment]
I have confirmed that it works with some modern Chromium-based browsers.
I haven't tried Edge, but it will probably work.

**Comment by katsukuro** [comment]
I tried it with Edge, it works! I've been testing with Edge for quite awhile for the Widevine L3 Decryptor to work on it, but finally this one works! I tried it with a Demo page so far it did return the keys

**Comment by yuusakurisub** [comment]
That's good.

**Comment by mahdisky** [comment]
> I got the file from the URL below. https://gofile.io/d/t6qwBQ
> 
> This is WidevineCdm for widevine-l3-decryptor to work.

can u send again?
its removed
